version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    ports:
      - "8081:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped